<?php

return [
    "Acinetobacter infections",
    "Actinomycosis",
    "African sleeping sickness (African trypanosomiasis)",
    "AIDS (Acquired immunodeficiency syndrome)",
    "Amebiasis",
    "Anaplasmosis",
    "Angiostrongyliasis",
    "Anisakiasis",
    "Anthrax",
    "Arcanobacterium haemolyticum infection",
    "Argentine hemorrhagic fever",
    "Ascariasis",
    "Aspergillosis",
    "Astrovirus infection",
    "Babesiosis",
    "Bacillus cereus infection",
    "Bacterial pneumonia",
    "Bacterial vaginosis",
    "Bacteroides infection",
    "Balantidiasis",
    "Bartonellosis",
    "Baylisascaris infection",
    "BK virus infection",
    "Black piedra",
    "Blastocystosis",
    "Blastomycosis",
    "Bolivian hemorrhagic fever",
    "Botulism (and Infant botulism)",
    "Brucellosis",
    "Bubonic plague",
    "Burkholderia infection",
    "Buruli ulcer",
    "Calicivirus infection (Norovirus and Sapovirus)",
    "Campylobacteriosis",
    "Candidiasis (Moniliasis; Thrush)",
    "Capillariasis",
    "Carrion's disease",
    "Cat-scratch disease",
    "Cellulitis",
    "Chagas Disease (American trypanosomiasis)",
    "Chancroid",
    "Chickenpox",
    "Chikungunya",
    "Chlamydia",
    "Chlamydophila pneumoniae infection",
    "Cholera Vibrio",
    "Chromoblastomycosis",
    "Chytridiomycosis",
    "Clonorchiasis",
    "Clostridium difficile colitis",
    "Coccidioidomycosis",
    "Colorado tick fever (CTF)",
    "Common cold (Acute viral rhinopharyngitis; Acute coryza)",
    "Creutzfeldt–Jakob disease (CJD)",
    "Crimean-Congo hemorrhagic fever (CCHF)",
    "Cryptococcosis",
    "Cryptosporidiosis",
    "Cutaneous larva migrans (CLM)",
    "Cyclosporiasis",
    "Cysticercosis",
    "Cytomegalovirus infection",
    "Dengue fever",
    "Desmodesmus infection",
    "Dientamoebiasis",
    "Diphtheria",
    "Diphyllobothriasis",
    "Dracunculiasis",
    "Ebola hemorrhagic fever",
    "Echinococcosis",
    "Ehrlichiosis",
    "Enterobiasis (Pinworm infection)",
    "Enterococcus infection",
    "Enterovirus infection",
    "Epidemic typhus",
    "Erythema infectiosum (Fifth disease)",
    "Exanthem subitum (Sixth disease)",
    "Fasciolasis",
    "Fasciolopsiasis",
    "Fatal familial insomnia (FFI)",
    "Filariasis",
    "Food poisoning",
    "Free-living amebic infection",
    "Fusobacterium infection",
    "Gas gangrene (Clostridial myonecrosis)",
    "Geotrichosis",
    "Gerstmann-Sträussler-Scheinker syndrome (GSS)",
    "Giardiasis",
    "Glanders",
    "Gnathostomiasis",
    "Gonorrhea",
    "Granuloma inguinale (Donovanosis)",
    "Group A streptococcal infection",
    "Group B streptococcal infection",
    "Haemophilus influenzae infection",
    "Hand, foot and mouth disease (HFMD)",
    "Hantavirus Pulmonary Syndrome (HPS)",
    "Heartland virus disease",
    "Helicobacter pylori infection",
    "Hemolytic-uremic syndrome (HUS)",
    "Hemorrhagic fever with renal syndrome (HFRS)",
    "Hepatitis A",
    "Hepatitis B",
    "Hepatitis C",
    "Hepatitis D",
    "Hepatitis E",
    "Herpes simplex",
    "Histoplasmosis",
    "Hookworm infection",
    "Human bocavirus infection",
    "Human ewingii ehrlichiosis",
    "Human granulocytic anaplasmosis (HGA)",
    "Human metapneumovirus infection",
    "Human monocytic ehrlichiosis",
    "Human papillomavirus (HPV) infection",
    "Human parainfluenza virus infection",
    "Hymenolepiasis",
    "Epstein–Barr virus infectious mononucleosis (Mono)",
    "Influenza (flu)",
    "Isosporiasis",
    "Kawasaki disease",
    "Keratitis",
    "Kingella kingae infection",
    "Kuru",
    "Lassa fever",
    "Legionellosis (Legionnaires' disease)",
    "Legionellosis (Pontiac fever)",
    "Leishmaniasis",
    "Leprosy",
    "Leptospirosis",
    "Listeriosis",
    "Lyme disease (Lyme borreliosis)",
    "Lymphatic filariasis (Elephantiasis)",
    "Lymphocytic choriomeningitis",
    "Malaria",
    "Marburg hemorrhagic fever (MHF)",
    "Measles",
    "Middle East respiratory syndrome (MERS)",
    "Melioidosis (Whitmore's disease)",
    "Meningitis",
    "Meningococcal disease",
    "Metagonimiasis",
    "Microsporidiosis",
    "Molluscum contagiosum (MC)",
    "Monkeypox",
    "Mumps",
    "Murine typhus (Endemic typhus)",
    "Mycoplasma pneumonia",
    "Mycetoma (disambiguation)",
    "Myiasis parasitic dipterous",
    "Neonatal conjunctivitis (Ophthalmia neonatorum)",
    "Norovirus (children and babies)",
    "Variant Creutzfeldt–Jakob disease (vCJD, nvCJD)",
    "Nocardiosis",
    "Onchocerciasis (River blindness)",
    "Opisthorchiasis",
    "Paracoccidioidomycosis (South American blastomycosis)",
    "Paragonimiasis",
    "Pasteurellosis",
    "Pediculosis capitis (Head lice)",
    "Pediculosis corporis (Body lice)",
    "Pediculosis pubis (Pubic lice, Crab lice)",
    "Pelvic inflammatory disease (PID)",
    "Pertussis (Whooping cough)",
    "Plague",
    "Pneumococcal infection",
    "Pneumocystis pneumonia (PCP)",
    "Pneumonia",
    "Poliomyelitis",
    "Prevotella infection",
    "Primary amoebic meningoencephalitis (PAM)",
    "Progressive multifocal leukoencephalopathy",
    "Psittacosis",
    "Q fever",
    "Rabies",
    "Relapsing fever",
    "Respiratory syncytial virus infection",
    "Rhinosporidiosis",
    "Rhinovirus infection",
    "Rickettsial infection",
    "Rickettsialpox",
    "Rift Valley fever (RVF)",
    "Rocky Mountain spotted fever (RMSF)",
    "Rotavirus infection",
    "Rubella",
    "Salmonellosis",
    "SARS (Severe Acute Respiratory Syndrome)",
    "Scabies",
    "Schistosomiasis",
    "Sepsis",
    "Shigellosis (Bacillary dysentery)",
    "Shingles (Herpes zoster)",
    "Smallpox (Variola)",
    "Sporotrichosis",
    "Staphylococcal food poisoning",
    "Staphylococcal infection",
    "Strongyloidiasis",
    "Subacute sclerosing panencephalitis",
    "Syphilis",
    "Taeniasis",
    "Tetanus (Lockjaw)",
    "Tinea barbae (Barber's itch)",
    "Tinea capitis (Ringworm of the Scalp)",
    "Tinea corporis (Ringworm of the Body)",
    "Tinea cruris (Jock itch)",
    "Tinea manum (Ringworm of the Hand)",
    "Tinea nigra",
    "Tinea pedis (Athlete’s foot)",
    "Tinea unguium (Onychomycosis)",
    "Tinea versicolor (Pityriasis versicolor)",
    "Toxocariasis (Ocular Larva Migrans (OLM))",
    "Toxocariasis (Visceral Larva Migrans (VLM))",
    "Trachoma",
    "Toxoplasmosis",
    "Trichinosis",
    "Trichomoniasis",
    "Trichuriasis (Whipworm infection)",
    "Tuberculosis",
    "Tularemia",
    "Typhoid fever",
    "Typhus fever",
    "Ureaplasma urealyticum infection",
    "Valley fever",
    "Venezuelan equine encephalitis",
    "Venezuelan hemorrhagic fever",
    "Vibrio vulnificus infection",
    "Vibrio parahaemolyticus enteritis",
    "Viral pneumonia",
    "West Nile Fever",
    "White piedra (Tinea blanca)",
    "Yersinia pseudotuberculosis infection",
    "Yersiniosis",
    "Yellow fever",
    "Zygomycosis"
];
